### ISSUE TITLE
Mounting volumes and permissions

### ISSUE THREAD

**Issue by Danielss89** [sherifabdlnaby/kubephp#33]
When a volume is mounted, either pvc or empty, they are mounted as root, and they cannot be chmodded or chowned(in init script), as the user in the pods is www-data(which is good).
The current way i'm handling this, is by creating an init pod, which actually uses root as user, and then run an init script.
Is this the best way to do it? Maybe kubephp should have an init container which uses root user?

**Comment by sherifabdlnaby** [comment]
@Danielss89 Yes, in Kubernetes use `fsGroup` option in the pod spec, this, in a nutshell, will add/change all files in the volumes (either PVCs or Tokens, etc) to be part of a group that is accessible to all Users (including www-data). This will be slow if you have PVCs with **tons of files**, but otherwise you won't notice any startup overhead.

**Comment by Danielss89** [comment]
I've tried that, and it doesn't really seems to work(not sure if i'm doing it wrong, but i've googled, and it seems like a lot of people have that issue).

**Comment by sherifabdlnaby** [comment]
@Danielss89 It does the trick with me, not sure about any other workaround, but the init container thing would work if you don't have explicit permissions not to run any container as root. In most of my cases, this wouldn't be an acceptable solution.
